/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinMentorRouteImport } from './routes/join-mentor'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestTestIdRouteImport } from './routes/test.$testId'
import { Route as TestResultAttemptIdRouteImport } from './routes/test-result.$attemptId'
import { Route as TestAnalysisTestIdRouteImport } from './routes/test-analysis.$testId'
import { Route as MentorDashboardRouteImport } from './routes/mentor.dashboard'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalRefundRouteImport } from './routes/legal/refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAuthRouteImport } from './routes/admin.auth'
import { Route as CourseKindIdRouteImport } from './routes/course.$kind.$id'

const JoinMentorRoute = JoinMentorRouteImport.update({
  id: '/join-mentor',
  path: '/join-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResultAttemptIdRoute = TestResultAttemptIdRouteImport.update({
  id: '/test-result/$attemptId',
  path: '/test-result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAnalysisTestIdRoute = TestAnalysisTestIdRouteImport.update({
  id: '/test-analysis/$testId',
  path: '/test-analysis/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorDashboardRoute = MentorDashboardRouteImport.update({
  id: '/mentor/dashboard',
  path: '/mentor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseKindIdRoute = CourseKindIdRouteImport.update({
  id: '/course/$kind/$id',
  path: '/course/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join-mentor': typeof JoinMentorRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/test-analysis/$testId': typeof TestAnalysisTestIdRoute
  '/test-result/$attemptId': typeof TestResultAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/course/$kind/$id': typeof CourseKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join-mentor': typeof JoinMentorRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/test-analysis/$testId': typeof TestAnalysisTestIdRoute
  '/test-result/$attemptId': typeof TestResultAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/course/$kind/$id': typeof CourseKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join-mentor': typeof JoinMentorRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/test-analysis/$testId': typeof TestAnalysisTestIdRoute
  '/test-result/$attemptId': typeof TestResultAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/course/$kind/$id': typeof CourseKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/join-mentor'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/mentor/dashboard'
    | '/test-analysis/$testId'
    | '/test-result/$attemptId'
    | '/test/$testId'
    | '/course/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/join-mentor'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/mentor/dashboard'
    | '/test-analysis/$testId'
    | '/test-result/$attemptId'
    | '/test/$testId'
    | '/course/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/join-mentor'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/mentor/dashboard'
    | '/test-analysis/$testId'
    | '/test-result/$attemptId'
    | '/test/$testId'
    | '/course/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinMentorRoute: typeof JoinMentorRoute
  AdminAuthRoute: typeof AdminAuthRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MentorDashboardRoute: typeof MentorDashboardRoute
  TestAnalysisTestIdRoute: typeof TestAnalysisTestIdRoute
  TestResultAttemptIdRoute: typeof TestResultAttemptIdRoute
  TestTestIdRoute: typeof TestTestIdRoute
  CourseKindIdRoute: typeof CourseKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join-mentor': {
      id: '/join-mentor'
      path: '/join-mentor'
      fullPath: '/join-mentor'
      preLoaderRoute: typeof JoinMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-result/$attemptId': {
      id: '/test-result/$attemptId'
      path: '/test-result/$attemptId'
      fullPath: '/test-result/$attemptId'
      preLoaderRoute: typeof TestResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-analysis/$testId': {
      id: '/test-analysis/$testId'
      path: '/test-analysis/$testId'
      fullPath: '/test-analysis/$testId'
      preLoaderRoute: typeof TestAnalysisTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/dashboard': {
      id: '/mentor/dashboard'
      path: '/mentor/dashboard'
      fullPath: '/mentor/dashboard'
      preLoaderRoute: typeof MentorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$kind/$id': {
      id: '/course/$kind/$id'
      path: '/course/$kind/$id'
      fullPath: '/course/$kind/$id'
      preLoaderRoute: typeof CourseKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinMentorRoute: JoinMentorRoute,
  AdminAuthRoute: AdminAuthRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
  MentorDashboardRoute: MentorDashboardRoute,
  TestAnalysisTestIdRoute: TestAnalysisTestIdRoute,
  TestResultAttemptIdRoute: TestResultAttemptIdRoute,
  TestTestIdRoute: TestTestIdRoute,
  CourseKindIdRoute: CourseKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
