/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestTestIdRouteImport } from './routes/test.$testId'
import { Route as TestResultAttemptIdRouteImport } from './routes/test-result.$attemptId'
import { Route as MentorDashboardRouteImport } from './routes/mentor.dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAuthRouteImport } from './routes/admin.auth'
import { Route as CourseKindIdRouteImport } from './routes/course.$kind.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResultAttemptIdRoute = TestResultAttemptIdRouteImport.update({
  id: '/test-result/$attemptId',
  path: '/test-result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorDashboardRoute = MentorDashboardRouteImport.update({
  id: '/mentor/dashboard',
  path: '/mentor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseKindIdRoute = CourseKindIdRouteImport.update({
  id: '/course/$kind/$id',
  path: '/course/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/test-result/$attemptId': typeof TestResultAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/course/$kind/$id': typeof CourseKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/test-result/$attemptId': typeof TestResultAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/course/$kind/$id': typeof CourseKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/test-result/$attemptId': typeof TestResultAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/course/$kind/$id': typeof CourseKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/profile'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/mentor/dashboard'
    | '/test-result/$attemptId'
    | '/test/$testId'
    | '/course/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/profile'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/mentor/dashboard'
    | '/test-result/$attemptId'
    | '/test/$testId'
    | '/course/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/profile'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/mentor/dashboard'
    | '/test-result/$attemptId'
    | '/test/$testId'
    | '/course/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ProfileRoute: typeof ProfileRoute
  AdminAuthRoute: typeof AdminAuthRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  MentorDashboardRoute: typeof MentorDashboardRoute
  TestResultAttemptIdRoute: typeof TestResultAttemptIdRoute
  TestTestIdRoute: typeof TestTestIdRoute
  CourseKindIdRoute: typeof CourseKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-result/$attemptId': {
      id: '/test-result/$attemptId'
      path: '/test-result/$attemptId'
      fullPath: '/test-result/$attemptId'
      preLoaderRoute: typeof TestResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/dashboard': {
      id: '/mentor/dashboard'
      path: '/mentor/dashboard'
      fullPath: '/mentor/dashboard'
      preLoaderRoute: typeof MentorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$kind/$id': {
      id: '/course/$kind/$id'
      path: '/course/$kind/$id'
      fullPath: '/course/$kind/$id'
      preLoaderRoute: typeof CourseKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ProfileRoute: ProfileRoute,
  AdminAuthRoute: AdminAuthRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  MentorDashboardRoute: MentorDashboardRoute,
  TestResultAttemptIdRoute: TestResultAttemptIdRoute,
  TestTestIdRoute: TestTestIdRoute,
  CourseKindIdRoute: CourseKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
